# BlockScanner Default Config

title = "BlockScanner"

[base]
folder = "chaindata"
debug = false

[blockchain]
protocol = "http:"
hostname = "127.0.0.1"
port = 8545
path = "/"

[database]
protocol = "mongodb:"
hostname = "127.0.0.1"
port = 27012
db = "CHAINDATA"
prefix = "BS_"
user = "BC2"
password = "password"

[api]
pathname = [
  "get|/version|Static.Utils.readPackageInfo",
  "get|/test/:go|Bot.BlockScanner.test|auth|hashcash"
]